name: CICD workflow for dev environment

on:
 push:
    branches:
      - feat/family

jobs:
  hello:
    runs-on: ubuntu-latest
    steps: 
      - name: step1
       run: date
      - name: step2
        run: |
          pwd
          ls
         
